name: Run Script in Container

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --cpus 4
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Python and pip
      run: |
        apt-get update
        apt-get install -y python3-pip
    
    - name: Install telebot
      run: |
        pip install pyTelegramBotAPI pymongo certifi requests aiohttp telebot --break-system-packages

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y proxychains
        # You might need to add custom installation steps for bgmi here

    - name: Set up MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: '5.0'
    - name: Make scripts executable
      run: |
        chmod +x *

    - name: Run infinite loop wrapper for m.py
      run: |
        chmod +x run_m_py.sh
        ./run_m_py.sh

